# Site
title:              Guia Programador
bio:                'Um Site Minimalista Sobre Meu Mundo na Programação.'
description:        'Guia Programador é um site desenvolvido por Jhonatan Mark, para expor suas idéias e aprendizados sobre Programação. PHP | Symfony | Bootstrap | Git | Etc.'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo2.png'
background:         'assets/img/back-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
url:                http://jhoemrs.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jhoemrs

# Social
# if you don't have any of social below, comment the line.
google:
  plus: JhonatanMark            #username
  analytics: UA-55748309-2
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              jhoemrs@gmail.com
twitter:            jhoemrs
facebook:           jhoemrs
github:             jhoemrs
stackoverflow:      21695/jhonatan-mark   #21695/jhonatan-mark from a "http://stackoverflow.com/users/123456/username" link
linkedin:           jhonatanmark
#xing:              username
instagram:          jhoemrs
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              jhoe
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
